#!/usr/bin/env python3
import os
import logging
from pyngrok import ngrok
from dotenv import load_dotenv, set_key

# Load .env
dotenv_path = ".env"
load_dotenv(dotenv_path)

# Ngrok token
NGROK_AUTH_TOKEN = "30dxkFANa3LoR0RV57mBFSs6Ndz_47MGq6BqgwQehk22KgeWz"
ngrok.set_auth_token(NGROK_AUTH_TOKEN)

# Start tunnel
logging.basicConfig(level=logging.INFO)
public_url = ngrok.connect(5000, bind_tls=True)
logging.info(f"Ngrok tunnel created: {public_url}")

# Update .env WEBHOOK_URL automatically
set_key(dotenv_path, "WEBHOOK_URL", f"{public_url}/webhook")
logging.info("Updated WEBHOOK_URL in .env")

# Start Ninja-dashboard bot
os.system("python3 start_icegods.py")
